import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const lexendZetta = localFont({
  src: "./fonts/LexendZetta-VariableFont_wght.woff",
  variable: "--font-lexend-zetta",
  weight: "100 900",
});
const jakartaSans = localFont({
  src: "./fonts/PlusJakartaSans-VariableFont_wght.woff",
  variable: "--font-jakarta-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendZetta.variable} ${jakartaSans.variable} antialiased dark:bg-gray-950`}
      >
        {children}
      </body>
    </html>
  );
}
